gejala_dict = {
    "cemas": "cemas",
    "diare": "diare",
    "gangguan siklus menstruasi": "gangguan siklus menstruasi",
    "gelisah": "gelisah",
    "gemetaran": "gemetaran",
    "gemuk": "gemuk",
    "masa lalu menakutkan": "masa lalu menakutkan",
    "ingin bunuh diri": "ingin bunuh diri",
    "iri": "iri",
    "kelaparan": "kelaparan",
    "keras kepala": "keras kepala",
    "keringat berlebihan": "keringat berlebihan",
    #batas
    "kewaspadaan berlebihan": "kewaspadaan berlebihan",
    "kulit kering": "kulit kering",
    "kurang fokus": "kurang fokus",
    "lemas": "lemas",
    "makan berlebihan": "makan berlebihan",
    "melakukan diet": "melakukan diet",
    "membutuhkan banyak pujian": "membutuhkan banyak pujian",
    "memeriksa sesuatu berulang": "memeriksa sesuatu berulang",
    "mempermasalahkan kerapian": "mempermasalahkan kerapian",
    "mempermasalahkan keteraturan": "mempermasalahkan keteraturan",
    "trauma": "trauma",
    "traumatis": "traumatis",
    "menyakiti diri sendiri": "menyakiti diri sendiri",
    "meragukan komitmen": "meragukan komitmen",
    "merasa istimewa": "merasa istimewa",
    "lebih baik dari orang lain": "lebih baik dari orang lain",
    "masa depan suram": "masa depan suram",
    "mual": "mual",
    "mudah lelah": "mudah lelah",
    "mudah tersinggung": "mudah tersinggung",
    "muntah": "muntah",
    "murung": "murung",
    "pembengkakan wajah": "pembengkakan wajah",
    "pembengkakan kelenjar di rahang": "pembengkakan kelenjar di rahang",
    "pengucapan kata yang tidak berarti": "pengucapan kata yang tidak berarti",
    "pengulangan kata": "pengulangan kata",
    "pengulangan tindakan": "pengulangan tindakan",
    "penurunan berat badan": "penurunan berat badan",
    "perasaan tidak menentu": "perasaan tidak menentu",
    "perubahan nafsu makan": "perubahan nafsu makan",
    "rambut rontok": "rambut rontok",
    "rasa bersalah": "rasa bersalah",
    "sakit kepala": "sakit kepala",
    "sakit perut": "sakit perut",
    "sakit tenggorokan": "sakit tenggorokan",
    "sangat kurus": "sangat kurus",
    "sensitif terhadap kritikan": "sensitif terhadap kritikan",
    "selalu merasa benar": "selalu merasa benar",
    "serangan panik": "serangan panik",
    "bermimpi buruk": "bermimpi buruk",
    "menghayal": "menghayal",
    "sombong": "sombong",
    "sulit berkonsentrasi": "sulit berkonsentrasi",
    "sulit mengambil keputusan": "sulit mengambil keputusan",
    "sulit tidur": "sulit tidur",
    "takut": "takut",
    "tidak berguna": "tidak berguna",
    "tidak empati": "tidak empati",
    "tidak peduli": "tidak peduli",
    "tidak mudah memaafkan": "tidak mudah memaafkan",
    "tidak percaya orang lain": "tidak percaya orang lain",
    "tidak percaya diri": "tidak percaya diri"
}

gejala_dict = dict(sorted(gejala_dict.items(), key=lambda x: len(x[0]), reverse=True))
