gejala_dict = {
    "cemas": "cemas",
    "diare": "diare",
    "ganggu siklus menstruasi": "ganggu siklus menstruasi",
    "gelisah": "gelisah",
    "gemetar": "gemetar",
    "gemuk": "gemuk",
    "takut masa lalu": "takut masa lalu",
    "bunuh diri": "bunuh diri",
    "iri": "iri",
    "lapar": "lapar",
    "keras kepala": "keras kepala",
    "keringat lebih": "keringat lebih",
    #batas
    "waspada lebih": "waspada lebih",
    "kulit kering": "kulit kering",
    "kurang fokus": "kurang fokus",
    "lemas": "lemas",
    "makan lebih": "makan lebih",
    "diet": "diet",
    "butuh pujian": "butuh pujian",
    "periksa suatu ulang": "periksa suatu ulang",
    "masalah rapi": "masalah rapi",
    "masalah teratur": "masalah teratur",
    "trauma": "trauma",
    "traumatis": "traumatis",
    "sakit diri sendiri": "sakit diri sendiri",
    "ragu komitmen": "ragu komitmen",
    "rasa istimewa": "rasa istimewa",
    "lebih baik dari orang lain": "lebih baik dari orang lain",
    "masa depan suram": "masa depan suram",
    "mual": "mual",
    "mudah lelah": "mudah lelah",
    "mudah tersinggung": "mudah tersinggung",
    "muntah": "muntah",
    "murung": "murung",
    "bengkak wajah": "bengkak wajah",
    "bengkak kelenjar rahang": "bengkak kelenjar rahang",
    "ucap kata tidak berarti": "ucap kata tidak berarti",
    "ulang kata": "ulang kata",
    "ulang tindakan": "ulang tindakan",
    "turun berat badan": "turun berat badan",
    "perasaan tidak menentu": "perasaan tidak menentu",
    "ubah nafsu makan": "ubah nafsu makan",
    "rambut rontok": "rambut rontok",
    "rasa bersalah": "rasa bersalah",
    "sakit kepala": "sakit kepala",
    "sakit perut": "sakit perut",
    "sakit tenggorok": "sakit tenggorok",
    "sangat kurus": "sangat kurus",
    "sensitif kritik": "sensitif kritik",
    "merasa benar": "merasa benar",
    "panik": "panik",
    "mimpi buruk": "mimpi buruk",
    "khayal": "khayal",
    "sombong": "sombong",
    "sulit konsentrasi": "sulit konsentrasi",
    "sulit ambil putus": "sulit ambil putus",
    "sulit tidur": "sulit tidur",
    "takut": "takut",
    "tidak berguna": "tidak berguna",
    "tidak empati": "tidak empati",
    "tidak peduli": "tidak peduli",
    "tidak mudah maaf": "tidak mudah maaf",
    "tidak percaya orang lain": "tidak percaya orang lain",
    "tidak percaya diri": "tidak percaya diri"
}

gejala_dict = dict(sorted(gejala_dict.items(), key=lambda x: len(x[0]), reverse=True))
